global:
  scrape_interval: 15s
  evaluation_interval: 15s

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - localhost:9093

rule_files:
  - "alert_rules.yml"

scrape_configs:
  - job_name: 'maria2-app'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['maria2-app:5000']

  - job_name: 'maria2-redis'
    static_configs:
      - targets: ['maria2-redis:6379']

  - job_name: 'node_exporter'
    static_configs:
      - targets: ['localhost:9100']

  - job_name: 'cadvisor'
    static_configs:
      - targets: ['localhost:8080']
